Supp.Site/Controllers/GoogleAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Supp.Models;
using Supp.Site.Repositories;
using Supp.Site.Common;
using System.Reflection;
using NLog;
using X.PagedList;
using static Supp.Site.Common.Config;
using Additional.NLog;
using GoogleManagerModels;

namespace Supp.Site.Controllers
{
    public class GoogleAccountsController : Controller
    {
        private readonly static Logger classLogger = LogManager.GetCurrentClassLogger();
        private readonly NLogUtility nLogUtility = new NLogUtility();
        private readonly GoogleAccountsRepository googleAccountRepo;
        private readonly SuppUtility suppUtility;
        private readonly GoogleAuthsRepository googleAuthRepo;
        private readonly UsersRepository userRepo;

        public GoogleAccountsController()
        {
            googleAccountRepo = new GoogleAccountsRepository(GeneralSettings.Static.BaseUrl);
            suppUtility = new SuppUtility();
            googleAuthRepo = new GoogleAuthsRepository(GeneralSettings.Static.BaseUrl);
            userRepo = new UsersRepository();
        }

        // GET: GoogleAccounts
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            using (var logger = new NLogScope(classLogger, nLogUtility.GetMethodToNLog(MethodInfo.GetCurrentMethod())))
            {
                GoogleAccountResult result = new GoogleAccountResult() { Data = new List<GoogleAccountDto>() { }, Successful = false };
                IEnumerable<GoogleAccountDto> data;

                try
                {
                    var currentMethod = nLogUtility.GetMethodToNLog(MethodInfo.GetCurrentMethod());
                    var method = currentMethod.Name;
                    var className = currentMethod.DeclaringType.Name;

                    ViewBag.CurrentSort = sortOrder;
                    ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Account" : "";

                    if (searchString != null)
                    {
                        page = 1;
                    }
                    else
                    {
                        searchString = currentFilter;
                    }

                    ViewBag.CurrentFilter = searchString;

                    var access_token_cookie = suppUtility.GetAccessToken(Request);

                    result = await googleAccountRepo.GetAllGoogleAccounts(access_token_cookie);

                    if (result.Successful == false)
                        throw new Exception($"Error - Class: [{className}, Method: [{method}], Operation: [{nameof(googleAccountRepo.GetAllGoogleAccounts)}] - Message: [{result.Message}]");

                    data = from s in result.Data
                           select s;

                    var users = userRepo.GetAllUsers(access_token_cookie).Result.Data.ToList();
                    var googleAuths = googleAuthRepo.GetAllGoogleAuths(access_token_cookie).Result.Data.ToList();

                    foreach (var row in data)
                    {
                        foreach (var user in users)
                        {
                            user.UserFullName = user.Surname + " " + user.Name;
                        }
                        row.Users = users;
                        row.GoogleAuths = googleAuths;
                    }

                    long val = 0;
                    Int64.TryParse(searchString, out val);

                    if (val != 0)
                    {
                        data = data.Where(_ => _.Id == val);
                    }
                    else if (!String.IsNullOrEmpty(searchString))
                    {
                        var _userIds = users.Where(_ => _.UserFullName.ToStringExtended().ToUpper().Contains(searchString.ToUpper().Trim())).Select(_ => _.Id).ToList();
                        var _googleAuthIds = googleAuths.Where(_ => _.Client_id.ToStringExtended().ToUpper().Contains(searchString.ToUpper().Trim())).Select(_ => _.Id).ToList();
                        data = data.Where(_ => _.Account.ToStringExtended().ToUpper().Contains(searchString.ToUpper().Trim())
                            || _.FolderToFilter.ToStringExtended().ToUpper().Contains(searchString.ToUpper().Trim())
                            || _.AccountType.ToStringExtended().ToUpper().Contains(searchString.ToUpper().Trim())
                            || _userIds.Contains(_.UserId)
                            || _googleAuthIds.Contains(_.GoogleAuthId)
                        );
                    }

                    switch (sortOrder)
                    {
                        case "Id":
                            data = data.OrderBy(_ => _.Id);
                            break;
                        case "Account":
                            data = data.OrderBy(_ => _.Account);
                            break;
                        case "FolderToFilter":
                            data = data.OrderBy(_ => _.FolderToFilter);
                            break;
                        case "GoogleAuthId":
                            data = data.OrderBy(_ => _.GoogleAuthId);
                            break;
                        case "GoogleAuthClient_id":
                            data = data.OrderBy(x => x.GoogleAuths.Where(_ => _.Id == x.GoogleAuthId).Select(_ => _.Client_id).FirstOrDefault());
                            break;
                        case "UserFullName":
                            data = data.OrderBy(x => x.Users.Where(_ => _.Id == x.UserId).Select(_ => _.UserFullName).FirstOrDefault());
                            break;
                        case "AccountType":
                            data = data.OrderBy(_ => _.AccountType);
                            break;
                        default:
                            data = data.OrderBy(_ => _.Account);
                            break;
                    }
                }
                catch (Exception ex)
                {
                    logger.Error(ex.ToString());
                    ModelState.AddModelError("ModelStateErrors", ex.Message);
                    suppUtility.AddErrorToCookie(Request, Response, ex.Message);

                    return RedirectToAction("Index", "Home");
                }

                if (result.Successful && result.Data.Count > 0)
                {
                    int pageSize = GeneralSettings.Static.PageSize;
                    int pageNumber = (page ?? 1);
                    return View(data.ToPagedList(pageNumber, pageSize));
                }
                else
                {
                    ModelState.AddModelError("ModelStateErrors", "GoogleAccounts not found!");
                    return View();
                }
            }
        }

        // GET: GoogleAccounts/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            using (var logger = new NLogScope(classLogger, nLogUtility.GetMethodToNLog(MethodInfo.GetCurrentMethod())))
            {
                try
                {
                    var currentMethod = nLogUtility.GetMethodToNLog(MethodInfo.GetCurrentMethod());
                    var method = currentMethod.Name;
                    var className = currentMethod.DeclaringType.Name;

                    if (id == null)
                        throw new Exception($"Error [Id is null!] - Class: [{className}, Method: [{method}], Operation: [] - Message: []");

                    var access_token_cookie = suppUtility.GetAccessToken(Request);
                    var result = await googleAccountRepo.GetGoogleAccountsById((long)id, access_token_cookie);
                    var data = result.Data.ToList();

                    var users = userRepo.GetAllUsers(access_token_cookie).Result.Data.ToList();
                    var googleAuths = googleAuthRepo.GetAllGoogleAuths(access_token_cookie).Result.Data.ToList();

                    foreach (var row in data)
                    {
                        foreach (var user in users)
                        {
                            user.UserFullName = user.Surname + " " + user.Name;
                        }
                        row.Users = users;
                        row.GoogleAuths = googleAuths;
                    }

                    if (result.Successful == false || data == null)
                        throw new Exception($"Error [Data not found!] - Class: [{className}, Method: [{method}], Operation: [{nameof(googleAccountRepo.GetGoogleAccountsById)}] - Message: [{result.Message}]");

                    return View(data.FirstOrDefault());
                }
                catch (Exception ex)
                {
                    logger.Error(ex.ToString());
                    ModelState.AddModelError("ModelStateErrors", ex.Message);
                    return View();
                }
            }
        }

        // GET: GoogleAccounts/Create
        public IActionResult Create()
        {
            using (var logger = new NLogScope(classLogger, nLogUtility.GetMethodToNLog(MethodInfo.GetCurrentMethod())))
            {
                try
                {
                    var currentMethod = nLogUtility.GetMethodToNLog(MethodInfo.GetCurrentMethod());
                    var method = currentMethod.Name;
                    var className = currentMethod.DeclaringType.Name;

                    var data = new List<GoogleAccountDto>() { };
                    var access_token_cookie = suppUtility.GetAccessToken(Request);

                    data.Add(new GoogleAccountDto() { });

                    var users = userRepo.GetAllUsers(access_token_cookie).Result.Data.ToList();
                    var googleAuths = googleAuthRepo.GetAllGoogleAuths(access_token_cookie).Result.Data.ToList();

Supp.Site/Views/GoogleAccounts/AddGoogleAccounts.cshtml
@model Supp.Models.GoogleAccountDto

@using Supp.Site.Controllers;

@{
    ViewData["Title"] = "Add Google Accounts";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = HomeController.Culture;
}

@using (Html.BeginForm("AddGoogleAccounts", "GoogleAccounts", FormMethod.Get))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <h1>@ViewData["Title"]</h1>

    <hr />

    <div>
        @if (Model != null)
        {

        }
        <div class="form-group">
            <a href="Downloads/GoogleCreateCredentialsTool.zip" download class = "btn btn-primary" style = "text-decoration: none;">Download Google Create Credentials Tool</a>
        </div>

    </div>

    <div class="text-danger" style="padding:30px;">
        @Html.ValidationSummary(false)
    </div>
}

Supp.Site/Views/GoogleAccounts/Create.cshtml
@model Supp.Models.GoogleAccountDto

@{
    ViewData["Title"] = "Create Google Drive Account";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Account" class="control-label"></label>
                <input asp-for="Account" class="form-control textBoxCustom" />
                <span asp-validation-for="Account" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FolderToFilter" class="control-label"></label>
                <input asp-for="FolderToFilter" class="form-control textBoxCustom" />
                <span asp-validation-for="FolderToFilter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GoogleAuths.FirstOrDefault().Client_id" class="control-label"></label>
                @Html.DropDownListFor(x => x.GoogleAuthId, new SelectList(Model.GoogleAuths, "Id", "GoogleAuthClient_id", Model.GoogleAuthId), "-- Select --", new { @class = "select" })
                @Html.ValidationMessageFor(x => x.GoogleAuthId)
            </div>
            <div class="form-group">
                <label asp-for="Users.FirstOrDefault().UserFullName" class="control-label"></label>
                @Html.DropDownListFor(x => x.UserId, new SelectList(Model.Users, "Id", "UserFullName", Model.UserId), "-- Select --", new { @class = "select" })
                @Html.ValidationMessageFor(x => x.UserId)
            </div>
            <div class="form-group">
                <label asp-for="AccountType" class="control-label"></label>
                @Html.DropDownListFor(x => x.AccountType, new SelectList(Model.AccountTypes, "Id", "AccountType", Model.AccountType), "-- Select --", new { @class = "select" })
                @Html.ValidationMessageFor(x => x.AccountType)
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<div class="text-danger" style="padding:30px;">
    @Html.ValidationSummary(false)
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Supp.Site/Views/GoogleAccounts/Delete.cshtml
@model Supp.Models.GoogleAccountDto

@{
    ViewData["Title"] = "Delete Google Drive Account";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Account)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Account)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.FolderToFilter)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.FolderToFilter)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.GoogleAuths.FirstOrDefault().Client_id)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.GoogleAuths.Where(_ => _.Id == model.GoogleAuthId).FirstOrDefault().Client_id)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Users.FirstOrDefault().UserFullName)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Users.Where(_ => _.Id == model.UserId).FirstOrDefault().UserFullName)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.AccountType)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.AccountType)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" /><input type="hidden" asp-for="InsDateTime" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

<div class="text-danger" style="padding:30px;">
    @Html.ValidationSummary(false)
</div>

Supp.Site/Views/GoogleAccounts/Details.cshtml
@model Supp.Models.GoogleAccountDto

@{
    ViewData["Title"] = "Details Google Drive Account";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Account)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Account)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.FolderToFilter)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.FolderToFilter)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.GoogleAuths.FirstOrDefault().Client_id)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.GoogleAuths.Where(_ => _.Id == model.GoogleAuthId).FirstOrDefault().Client_id)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Users.FirstOrDefault().UserFullName)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Users.Where(_ => _.Id == model.UserId).FirstOrDefault().UserFullName)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.AccountType)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.AccountType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

<div class="text-danger" style="padding:30px;">
    @Html.ValidationSummary(false)
</div>

Supp.Site/Views/GoogleAccounts/Edit.cshtml
@model Supp.Models.GoogleAccountDto

@{
    ViewData["Title"] = "Edit Google Drive Account";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        @if (Model != null)
        {
            <form asp-action="Edit"><input type="hidden" asp-for="Id" /><input type="hidden" asp-for="InsDateTime" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" /><input type="hidden" asp-for="InsDateTime" />
            <div class="form-group">
                <label asp-for="Account" class="control-label"></label>
                <input asp-for="Account" class="form-control textBoxCustom" />
                <span asp-validation-for="Account" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FolderToFilter" class="control-label"></label>
                <input asp-for="FolderToFilter" class="form-control textBoxCustom" />
                <span asp-validation-for="FolderToFilter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GoogleAuths.FirstOrDefault().Client_id" class="control-label"></label>
                @Html.DropDownListFor(x => x.GoogleAuthId, new SelectList(Model.GoogleAuths, "Id", "GoogleAuthClient_id", Model.GoogleAuthId), "-- Select --", new { @class = "select" })
                @Html.ValidationMessageFor(x => x.GoogleAuthId)
            </div>
            <div class="form-group">
                <label asp-for="Users.FirstOrDefault().UserFullName" class="control-label"></label>
                @Html.DropDownListFor(x => x.UserId, new SelectList(Model.Users, "Id", "UserFullName", Model.UserId), "-- Select --", new { @class = "select" })
                @Html.ValidationMessageFor(x => x.UserId)
            </div>
            <div class="form-group">
                <label asp-for="AccountType" class="control-label"></label>
                @Html.DropDownListFor(x => x.AccountType, new SelectList(Model.AccountTypes, "Id", "AccountType", Model.AccountType), "-- Select --", new { @class = "select" })
                @Html.ValidationMessageFor(x => x.AccountType)
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<div class="text-danger" style="padding:30px;">
    @Html.ValidationSummary(false)
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Supp.Site/Views/GoogleAccounts/Index.cshtml
@model X.PagedList.IPagedList<Supp.Models.GoogleAccountDto>

@using Supp.Site.Controllers;
@using X.PagedList.Mvc.Core

<link href="~/css/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewData["Title"] = "GoogleAccount List";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = HomeController.Culture;
}

@using (Html.BeginForm("Index", "GoogleAccounts", FormMethod.Get))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <h1>@ViewData["Title"]</h1>

    <hr />

    <div>
        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <p>
            Find: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" class="btn btn-primary" style="margin-top:-2px;" />
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th id="borderTitle"></th>
                    <th id="selectable">
                        @Html.ActionLink("Account", "Index", new { sortOrder = "Account", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("FolderToFilter", "Index", new { sortOrder = "FolderToFilter", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("GoogleAuthClient_id", "Index", new { sortOrder = "GoogleAuthClient_id", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("UserFullName", "Index", new { sortOrder = "UserFullName", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("AccountType", "Index", new { sortOrder = "AccountType", currentFilter = ViewBag.CurrentFilter })
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var item in Model)
                    {
                <tr>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Account)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FolderToFilter)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GoogleAuths.Where(_ => _.Id == item.GoogleAuthId).FirstOrDefault().Client_id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Users.Where(_ => _.Id == item.UserId).FirstOrDefault().UserFullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AccountType)
                    </td>
                </tr>
                    }
                }
            </tbody>
        </table>
    </div>

    <div class="text-danger" style="padding:30px;">
        @Html.ValidationSummary(false)
    </div>
}
    Page @if (Model != null)
{@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)} of @if (Model != null)
    {@Model.PageCount}

@if (Model != null)
{@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))}