Supp.Site/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Supp.Models;
using Supp.Site.Repositories;
using Supp.Site.Common;
using System.Reflection;
using NLog;
using X.PagedList;
using static Supp.Site.Common.Config;
using Additional.NLog;
using AutoMapper;
using Newtonsoft.Json;
using GoogleManagerModels;
using Google.Apis.Calendar.v3.Data;

namespace Supp.Site.Controllers
{
    public class MediaController : Controller
    {
        private readonly static Logger classLogger  = LogManager.GetCurrentClassLogger();
        private readonly  NLogUtility nLogUtility = new NLogUtility();
        private readonly MediaRepository mediaRepo;
        private readonly SuppUtility suppUtility;
        private readonly GoogleAccountsRepository googleAccountRepository;
        

        public MediaController()
        {
            mediaRepo = new MediaRepository();
            googleAccountRepository = new GoogleAccountsRepository(GeneralSettings.Static.BaseUrl);
            suppUtility = new SuppUtility();
        }

        // GET: Media
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            using (var logger = new NLogScope(classLogger, nLogUtility.GetMethodToNLog(MethodInfo.GetCurrentMethod())))
            {
                MediaResult result = new MediaResult() { Data = new List<MediaDto>() { }, Successful = false };
                IEnumerable<MediaDto> data;

                try
                {
                    var currentMethod = nLogUtility.GetMethodToNLog(MethodInfo.GetCurrentMethod());
                    var method = currentMethod.Name;
                    var className = currentMethod.DeclaringType.Name;

                    ViewBag.CurrentSort = sortOrder;
                    ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "UserName" : "";

                    if (searchString != null)
                    {
                        page = 1;
                    }
                    else
                    {
                        searchString = currentFilter;
                    }

                    ViewBag.CurrentFilter = searchString;

                    var access_token_cookie = suppUtility.GetAccessToken(Request);

                    result = await mediaRepo.GetAllMedia(access_token_cookie);

                    if (result.Successful == false)
                        throw new Exception($"Error - Class: [{className}, Method: [{method}], Operation: [{nameof(mediaRepo.GetAllMedia)}] - Message: [{result.Message}]");

                    data = from s in result.Data
                           select s;

                    var googleAccountResult = await googleAccountRepository.GetAllGoogleAccounts(access_token_cookie);

                    if (!googleAccountResult.Successful)
                        throw new Exception(nameof(googleAccountRepository.GetAllGoogleAccounts) + " " + googleAccountResult.Message + "!");

                    foreach (var row in data)
                    {
                        row.GoogleAccounts = googleAccountResult.Data;
                    }

                    long val = 0;
                    Int64.TryParse(searchString, out val);

                    if (val != 0)
                    {
                        data = data.Where(_ => _.Id == val);
                    }
                    else if (!String.IsNullOrEmpty(searchString))
                    {
                        var _googleAccountIds = googleAccountResult.Data.Where(_ => _.Account.ToStringExtended().ToUpper().Contains(searchString.ToUpper().Trim())).Select(_ => _.Id).ToList();
                        data = data.Where(_ => _.UserName.ToStringExtended().ToUpper().Contains(searchString.ToUpper().Trim())
                            || _.Name.ToStringExtended().ToUpper().Contains(searchString.ToUpper().Trim())
                            || _.FileId.ToStringExtended().ToUpper().Contains(searchString.ToUpper().Trim())
                            || _googleAccountIds.Contains(_.GoogleAccountId)
                        );
                    }

                    switch (sortOrder)
                    {
                        case "Id":
                            data = data.OrderBy(_ => _.Id);
                            break;
                        case "GoogleAccount":
                            data = data.OrderBy(_ => _.GoogleAccounts.Where(x => x.Id== _.GoogleAccountId).Select(_ => _.Account).FirstOrDefault());
                            break;
                        case "FileId":
                            data = data.OrderBy(_ => _.FileId);
                            break;
                        case "Name":
                            data = data.OrderBy(_ => _.Name);
                            break;
                        case "Path":
                            data = data.OrderBy(_ => _.Path);
                            break;
                        case "ModifiedTime":
                            data = data.OrderBy(_ => _.ModifiedTime);
                            break;
                        case "CreatedTime":
                            data = data.OrderBy(_ => _.CreatedTime);
                            break;
                        case "Size":
                            data = data.OrderBy(_ => _.Size);
                            break;
                        case "FileExtension":
                            data = data.OrderBy(_ => _.FileExtension);
                            break;
                        case "MimeType":
                            data = data.OrderBy(_ => _.MimeType);
                            break;
                        case "VideoDurationMillis":
                            data = data.OrderBy(_ => _.VideoDurationMillis);
                            break;
                        case "VideoHeight":
                            data = data.OrderBy(_ => _.VideoHeight);
                            break;
                        case "VideoWidth":
                            data = data.OrderBy(_ => _.VideoWidth);
                            break;
                        case "ImageTime":
                            data = data.OrderBy(_ => _.ImageTime);
                            break;
                        case "ImageWidth":
                            data = data.OrderBy(_ => _.ImageWidth);
                            break;
                        case "ImageHeight":
                            data = data.OrderBy(_ => _.ImageHeight);
                            break;
                        case "ImageLocationAltitude":
                            data = data.OrderBy(_ => _.ImageLocationAltitude);
                            break;
                        case "ImageLocationLatitude":
                            data = data.OrderBy(_ => _.ImageLocationLatitude);
                            break;
                        case "ImageLocationLongitude":
                            data = data.OrderBy(_ => _.ImageLocationLongitude);
                            break;
                        case "UserName":
                            data = data.OrderBy(_ => _.UserName);
                            break;
                        case "Type":
                            data = data.OrderBy(_ => _.Type);
                            break;
                        case "File":
                            data = data.OrderBy(_ => _.File);
                            break;
                        case "Thumbnail":
                            data = data.OrderBy(_ => _.Thumbnail);
                            break;
                        case "ThumbnailWidth":
                            data = data.OrderBy(_ => _.ThumbnailWidth);
                            break;
                        case "ThumbnailHeight":
                            data = data.OrderBy(_ => _.ThumbnailHeight);
                            break;
                        default:
                            data = data.OrderBy(_ => _.UserName);
                            break;
                    }
                }
                catch (Exception ex)
                {
                    logger.Error(ex.ToString());
                    ModelState.AddModelError("ModelStateErrors", ex.Message);
                    suppUtility.AddErrorToCookie(Request, Response, ex.Message);

                    return RedirectToAction("Index", "Home");
                }

                if (result.Successful && result.Data.Count > 0)
                {
                    int pageSize = GeneralSettings.Static.PageSize;
                    int pageNumber = (page ?? 1);
                    return View(data.ToPagedList(pageNumber, pageSize));
                }
                else
                {
                    ModelState.AddModelError("ModelStateErrors", "Media not found!");
                    return View();
                }
            }
        }

        // GET: Media/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            using (var logger = new NLogScope(classLogger, nLogUtility.GetMethodToNLog(MethodInfo.GetCurrentMethod())))
            {
                try
                {
                    var currentMethod = nLogUtility.GetMethodToNLog(MethodInfo.GetCurrentMethod());
                    var method = currentMethod.Name;
                    var className = currentMethod.DeclaringType.Name;

                    if (id == null)
                        throw new Exception($"Error [Id is null!] - Class: [{className}, Method: [{method}], Operation: [] - Message: []");

                    var access_token_cookie = suppUtility.GetAccessToken(Request);
                    var result = await mediaRepo.GetMediaById((long)id, access_token_cookie);
                    var data = result.Data.ToList();

Supp.Site/Views/Media/Create.cshtml
@model Supp.Models.MediaDto

@{
    ViewData["Title"] = "Create Media";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GoogleAccounts.FirstOrDefault().Account" class="control-label"></label>
                @Html.DropDownListFor(x => x.GoogleAccountId, new SelectList(Model.GoogleAccounts, "Id", "Account", Model.GoogleAccountId), "-- Select --", new { @class = "select" })
                @Html.ValidationMessageFor(x => x.GoogleAccountId)
            </div>
            <div class="form-group">
                <label asp-for="FileId" class="control-label"></label>
                <input asp-for="FileId" class="form-control textBoxCustom" />
                <span asp-validation-for="FileId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control textBoxCustom" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <input asp-for="Path" class="form-control textBoxCustom" />
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedTime" class="control-label"></label>
                <input asp-for="ModifiedTime" class="form-control textBoxCustom" />
                <span asp-validation-for="ModifiedTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedTime" class="control-label"></label>
                <input asp-for="CreatedTime" class="form-control textBoxCustom" />
                <span asp-validation-for="CreatedTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size" class="control-label"></label>
                <input asp-for="Size" class="form-control textBoxCustom" />
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FileExtension" class="control-label"></label>
                <input asp-for="FileExtension" class="form-control textBoxCustom" />
                <span asp-validation-for="FileExtension" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MimeType" class="control-label"></label>
                <input asp-for="MimeType" class="form-control textBoxCustom" />
                <span asp-validation-for="MimeType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VideoDurationMillis" class="control-label"></label>
                <input asp-for="VideoDurationMillis" class="form-control textBoxCustom" />
                <span asp-validation-for="VideoDurationMillis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VideoHeight" class="control-label"></label>
                <input asp-for="VideoHeight" class="form-control textBoxCustom" />
                <span asp-validation-for="VideoHeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VideoWidth" class="control-label"></label>
                <input asp-for="VideoWidth" class="form-control textBoxCustom" />
                <span asp-validation-for="VideoWidth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageTime" class="control-label"></label>
                <input asp-for="ImageTime" class="form-control textBoxCustom" />
                <span asp-validation-for="ImageTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageWidth" class="control-label"></label>
                <input asp-for="ImageWidth" class="form-control textBoxCustom" />
                <span asp-validation-for="ImageWidth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageHeight" class="control-label"></label>
                <input asp-for="ImageHeight" class="form-control textBoxCustom" />
                <span asp-validation-for="ImageHeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageLocationAltitude" class="control-label"></label>
                <input asp-for="ImageLocationAltitude" class="form-control textBoxCustom" />
                <span asp-validation-for="ImageLocationAltitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageLocationLatitude" class="control-label"></label>
                <input asp-for="ImageLocationLatitude" class="form-control textBoxCustom" />
                <span asp-validation-for="ImageLocationLatitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageLocationLongitude" class="control-label"></label>
                <input asp-for="ImageLocationLongitude" class="form-control textBoxCustom" />
                <span asp-validation-for="ImageLocationLongitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control textBoxCustom" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control textBoxCustom" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" class="form-control textBoxCustom" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thumbnail" class="control-label"></label>
                <input asp-for="Thumbnail" class="form-control textBoxCustom" />
                <span asp-validation-for="Thumbnail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThumbnailWidth" class="control-label"></label>
                <input asp-for="ThumbnailWidth" class="form-control textBoxCustom" />
                <span asp-validation-for="ThumbnailWidth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThumbnailHeight" class="control-label"></label>
                <input asp-for="ThumbnailHeight" class="form-control textBoxCustom" />
                <span asp-validation-for="ThumbnailHeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<div class="text-danger" style="padding:30px;">
    @Html.ValidationSummary(false)
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Supp.Site/Views/Media/Index.cshtml
@model X.PagedList.IPagedList<Supp.Models.MediaDto>

@using Supp.Site.Controllers;
@using X.PagedList.Mvc.Core

<link href="~/css/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewData["Title"] = "Media List";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = HomeController.Culture;
}

@using (Html.BeginForm("Index", "Media", FormMethod.Get))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <h1>@ViewData["Title"]</h1>

    <hr />

    <div>
        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <p>
            Find: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" class="btn btn-primary" style="margin-top:-2px;" />
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th id="borderTitle"></th>
                    <th id="selectable">
                        @Html.ActionLink("GoogleAccount", "Index", new { sortOrder = "GoogleAccount", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("FileId", "Index", new { sortOrder = "FileId", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("Name", "Index", new { sortOrder = "Name", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("Path", "Index", new { sortOrder = "Path", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("ModifiedTime", "Index", new { sortOrder = "ModifiedTime", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("CreatedTime", "Index", new { sortOrder = "CreatedTime", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("Size", "Index", new { sortOrder = "Size", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("FileExtension", "Index", new { sortOrder = "FileExtension", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("MimeType", "Index", new { sortOrder = "MimeType", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("VideoDurationMillis", "Index", new { sortOrder = "VideoDurationMillis", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("VideoHeight", "Index", new { sortOrder = "VideoHeight", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("VideoWidth", "Index", new { sortOrder = "VideoWidth", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("ImageTime", "Index", new { sortOrder = "ImageTime", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("ImageWidth", "Index", new { sortOrder = "ImageWidth", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("ImageHeight", "Index", new { sortOrder = "ImageHeight", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("ImageLocationAltitude", "Index", new { sortOrder = "ImageLocationAltitude", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("ImageLocationLatitude", "Index", new { sortOrder = "ImageLocationLatitude", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("ImageLocationLongitude", "Index", new { sortOrder = "ImageLocationLongitude", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("UserName", "Index", new { sortOrder = "UserName", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("Type", "Index", new { sortOrder = "Type", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("File", "Index", new { sortOrder = "File", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("Thumbnail", "Index", new { sortOrder = "Thumbnail", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("ThumbnailWidth", "Index", new { sortOrder = "ThumbnailWidth", currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th id="selectable">
                        @Html.ActionLink("ThumbnailHeight", "Index", new { sortOrder = "ThumbnailHeight", currentFilter = ViewBag.CurrentFilter })
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var item in Model)
                    {
                <tr>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GoogleAccounts.Where(_ => _.Id == item.GoogleAccountId).FirstOrDefault().Account)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FileId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Path)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Size)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FileExtension)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MimeType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VideoDurationMillis)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VideoHeight)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VideoWidth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ImageTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ImageWidth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ImageHeight)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ImageLocationAltitude)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ImageLocationLatitude)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ImageLocationLongitude)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @(item.File.Length > 0)
                    </td>
                    <td>
                        @(item.Thumbnail.Length > 0)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ThumbnailWidth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ThumbnailHeight)
                    </td>
                </tr>
                    }
                }
            </tbody>
        </table>
    </div>

    <div class="text-danger" style="padding:30px;">
        @Html.ValidationSummary(false)
    </div>
}
    Page @if (Model != null)
{@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)} of @if (Model != null)
    {@Model.PageCount}

@if (Model != null)
{@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))}

Supp.Site/Views/Media/MediaBox.cshtml
@model List<Supp.Models.MediaDto>

@using Supp.Site.Controllers;


@{
    ViewData["Title"] = "Media Box";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = HomeController.Culture;
}

@using (Html.BeginForm("MediaBox", "Media", FormMethod.Get))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div style="position:relative; ">
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <div style="float:left; position:relative;">
                    <img src="data:image/png;base64,@(Convert.ToBase64String(item.Thumbnail, Base64FormattingOptions.InsertLineBreaks))">
                </div>
            }
        }
    </div>

    <div class="text-danger" style="padding:30px;">
        @Html.ValidationSummary(false)
    </div>
}

Supp.Site/Views/Media/StructureMedia.cshtml
@model GoogleManagerModels.RequestResult

@using Supp.Site.Controllers;

@{
    ViewData["Title"] = "Structure Media";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = HomeController.Culture;
}

@using (Html.BeginForm("StructureMedia", "Media", FormMethod.Get))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <h1>@ViewData["Title"]</h1>

    <hr />

    <div>
        @if (Model != null)
        {
            <p>
                <dl class="row">
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.Successful)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.Successful)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.ResultState)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.ResultState)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.Message)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.Message)
                    </dd>
                    <br />
                    <dt class="col-sm-3">
                        Elements founded
                        
                    </dt>
                    <dd class="col-sm-9">
                        @{
                            var totElements = 0;
                            foreach (var item in Model.Data)
                            {
                                totElements += item.Files.Count();
                            }
                        }
                        @totElements
                    </dd>
                </dl>
            </p>
        }
    <div class="form-group">
        @Html.ActionLink("Clear Structure Media", "StructureMedia", new { mediaRequested = true, clear = true}, new { @class = "btn btn-danger", @style = "text-decoration: none;" })
        @Html.ActionLink("Get Structure Media", "StructureMedia", new { mediaRequested = true, clear = false}, new { @class = "btn btn-primary", @style = "text-decoration: none;" })       
    </div>

    </div>

    <div class="text-danger" style="padding:30px;">
        @Html.ValidationSummary(false)
    </div>
}